/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package car_wash;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danial
 */
public class Staff_Info extends javax.swing.JFrame {
    
    public void DeleteStaff(){
            Database2 db=new Database2();
        ResultSet rs=db.getdata2();
            try{
                while(rs.next()){
                    String data[]={rs.getString("Staff_Name"), rs.getString("Staff_Number"),rs.getString("Staff_Email")};
                    DefaultTableModel tfd=(DefaultTableModel)SItable.getModel();
                    tfd.addRow(data);
                }
            }
            catch(Exception e){
                System.out.println(e);
            
        }
       
        
    }
   
    public Staff_Info() {
        initComponents();
        DeleteStaff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SE = new javax.swing.JTextField();
        SNo = new javax.swing.JTextField();
        SN = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        SItable = new javax.swing.JTable();
        update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 11, 386, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        jLabel2.setText("Staff Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        jLabel4.setText("Staff Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 141, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        jLabel9.setText("Staff Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 203, -1, -1));
        getContentPane().add(SE, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 199, 110, -1));
        getContentPane().add(SNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 142, 110, -1));
        getContentPane().add(SN, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 79, 110, -1));

        SItable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff Name", "Staff Number", "Staff Email"
            }
        ));
        SItable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SItableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SItableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(SItable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 79, -1, 140));

        update.setBackground(new java.awt.Color(51, 51, 255));
        update.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        update.setText("Add");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 255, 0));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car_wash/staffinfo.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SItableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SItableMouseClicked
        // mouse click action performed
        int index = SItable.getSelectedRow();
        DefaultTableModel dbt = (DefaultTableModel) SItable.getModel();
        SN.setText(dbt.getValueAt(index, 0).toString());
        SNo.setText(dbt.getValueAt(index, 1).toString());
        SE.setText(dbt.getValueAt(index, 2).toString());

    }//GEN-LAST:event_SItableMouseClicked

    private void SItableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SItableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SItableMousePressed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(SN.getText().equals("")||SNo.getText().equals("")||SE.getText().equals("")){
            JOptionPane.showMessageDialog(null,"All Fields Are Required!");
            
              }
        else{ 
        Database2 db=new Database2();
        
       db.insertStaff(SN.getText(),Integer.parseInt(SNo.getText()),SE.getText());
       SN.setText(null);
       SNo.setText(null);
       SE.setText(null);
      
         JOptionPane.showMessageDialog(null,"Added Successfully!!!!!!");
         
       
       ResultSet rs=db.getdata2();
       try{
            while(rs.next()){
            String data[]={rs.getString("Staff_Name"),rs.getString("Staff_Number"), rs.getString("Staff_Email")};
            DefaultTableModel tfd=(DefaultTableModel)SItable.getModel();
            
            tfd.addRow(data);
        }
       }
       catch(Exception e){
           System.out.println(e);
       }
                }
    }//GEN-LAST:event_updateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Database2 db=new Database2();
           db.deletestaff(SN.getText());
       
        DefaultTableModel tfd=(DefaultTableModel)SItable.getModel();
        tfd.setRowCount(0);
        DeleteStaff();
      
        
        JOptionPane.showMessageDialog(null,"Deleted Successfully!!!!!!");
        
        
        
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SN.setText(null);
        SNo.setText(null);
        SE.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SE;
    private javax.swing.JTable SItable;
    private javax.swing.JTextField SN;
    private javax.swing.JTextField SNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
